# Default configuration for DataProwler

# API settings
api:
  host: 0.0.0.0
  port: 8000
  debug: false
  request_timeout: 30
  max_content_length: 10485760  # 10MB

# Search engine settings
search:
  engines:
    - google
    - bing
  max_results: 20
  timeout: 10
  google:
    api_key: ""
    cx: ""
    country: "us"
  bing:
    api_key: ""
    country: "us"

# Web scraping settings
scraping:
  timeout: 30
  retry:
    max_retries: 3
    backoff_factor: 2
    status_forcelist: [429, 500, 502, 503, 504]
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
  respect_robots_txt: true
  javascript_enabled: true
  wait_for_selectors: true
  wait_time: 5
  scroll_behavior:
    enabled: true
    max_scrolls: 5
    wait_time: 1.5

# Anti-bot detection settings
anti_bot:
  use_proxies: false
  proxies: []
  rotate_user_agents: true
  mimic_human_behavior: true
  handle_captchas: false
  captcha_service: ""
  captcha_api_key: ""

# Rate limiting settings
rate_limiting:
  enabled: true
  requests_per_minute: 10  # Default global rate limit
  domain_specific:
    "example.com": 5
    "api.example.org": 20

# ML model settings
ml:
  content_extraction:
    model_path: ""
    threshold: 0.7
  query_processing:
    model_path: ""
    max_tokens: 1024

# Database settings
database:
  url: "sqlite:///dataprowler.db"
  pool_size: 5
  max_overflow: 10
  echo: false

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: ""  # Empty string disables file logging

# Cache settings
cache:
  enabled: true
  type: "memory"  # Options: memory, redis, filesystem
  ttl: 3600  # Time to live in seconds
  max_size: 1000  # Max entries for memory cache
  redis:
    host: "localhost"
    port: 6379
    db: 0
  filesystem:
    path: ".cache"

# Performance settings
performance:
  max_workers: 4
  timeout: 60
  memory_limit: 0  # 0 means no limit

# Features toggles
features:
  use_ml_processing: true
  advanced_extraction: true
  site_structure_learning: true